---
title: ""
subtitle: ""
author: "Seth Eshraghi"
date: ""
output:
  pdf_document:
    highlight: haddock
keep_tex: no
number_sections: no
html_document:
    df_print: paged
geometry: margin = 0.5in
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
- \usepackage{empheq}
- \graphicspath{{./assets/}}
editor_options:
  chunk_output_type: console
documentclass: article
urlcolor: blue
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,
                      comment = NA,
                      fig.path = "./assets/",
                      fig.align = "center",
                      fig.width = 6,
                      fig.height = 6,
                      message = FALSE,
                      warning = FALSE
                      )
```

```{r include=FALSE}
setwd("~/Documents/vt/school-repo/")
```

\newpage
